---
- name: Install a new debian system
  hosts: external

  vars:
    zfs_system_root_name: "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"

  handlers:
    - name: Restart sshd
      systemd:
        name: sshd
        state: restarted

  tasks:
    - name: Ensure the debian version is defined
      assert:
        that:
          - ansible_distribution_release is defined
          - ansible_distribution_release != "n/a"

    - name: Setup the live environment
      ansible.builtin.import_tasks: tasks/setup_live_environment.yml

    - name: Install the system
      ansible.builtin.import_tasks: tasks/install_system.yml


- name: Install a new debian system
  hosts: external

  vars:
    ansible_port: 8922
    zfs_system_root_name: "{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"

  tasks:
    - name: Setup the system
      ansible.builtin.import_tasks: tasks/setup_system.yml

- name: Cleanup post installation
  hosts: external

  tasks:
    - name: Kill lingering ssh session
      delegate_to: 127.0.0.1
      ansible.builtin.command:
        cmd: ssh -O stop root@{{ inventory_hostname }} -p 8922
      changed_when: true

    - name: Unmount filesystems
      command: umount /mnt/{{ item }}
      loop:
        - boot/efi
        - dev
        - proc
        - run
        - tmp
        - sys/firmware/efi/efivars
        - sys

    - name: Export zfs filesystems
      become: true
      command: zpool export -a
