---
- name: Destroy container instances
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Get all running VMs
      community.libvirt.virt:
        command: list_vms
        uri: qemu:///session
      register: _all_vms

    - name: Stop the VM gracefully
      community.libvirt.virt:
        name: "{{ groups['external'] | first }}"
        state: shutdown
        uri: qemu:///session
      when: groups['external'][0] in _all_vms.list_vms

    - name: Wait for the VM to be off
      community.libvirt.virt:
        name: "{{ groups['external'] | first }}"
        command: status
        uri: qemu:///session
      until: _vm_stat.status == "shutdown"
      retries: 10
      delay: 1
      register: _vm_stat
      when: groups['external'][0] in _all_vms.list_vms

    - name: Destroy the Virtual Machine
      community.libvirt.virt:
        name: "{{ groups['external'] | first }}"
        command: undefine
        force: true
        uri: qemu:///session
      when: groups['external'][0] in _all_vms.list_vms
