---
- name: Validate the newly installed OS
  hosts: molecule

  vars:
    ansible_become_pass: "{{ admin_password_clear }}"

  tasks:
    ##
    # Internet connectivity
    ##
    - name: Ensure host has internet connectivity
      ansible.builtin.wait_for:
        host: "{{ ansible_facts.default_ipv4.gateway }}"
        port: 53
        timeout: 1

    - name: Ensure host can resolve hostnames
      ansible.builtin.wait_for:
        host: www.google.com
        port: 80
        timeout: 1

    ##
    # Filesystems
    ##
    - name: Load the fstab content
      become: true
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab

    - name: Ensure the fstab contains the expected number of lines
      ansible.builtin.assert:
        that: (fstab.content | b64decode | regex_findall("\\S.*") | length) == (root_disks | length + 2)
        msg: |
          Expected {{ root_disks | length + 2 }} entries in fstab. Got {{ fstab.content | b64decode | regex_findall("\\S.*") | length }} instead:
          ---
          {{ fstab.content | b64decode }}
          ---

    - name: Ensure the boot/efi directory is properly mirrored
      become: true
      ansible.builtin.command:
        cmd: diff --exclude .esp-* --brief /boot/efi /boot/efi/.esp-{{ item }}
      changed_when: false
      loop: "{{ root_disks[1:] }}"

    ##
    # Software is up to date
    ##
    - name: Get the status of the proxy file
      ansible.builtin.file:
        path: /etc/apt/apt.conf.d/80-use-proxy
        state: absent
      check_mode: true
      register: _proxy_config

    - name: Ensure no packages need update
      ansible.builtin.assert:
        that: not _proxy_config.changed
        msg: 80-use-proxy should have been deleted

    - name: Ensure the apt cache is up to date
      become: true
      ansible.builtin.apt:
        update_cache: true

    - name: Check what packages would need an update
      become: true
      ansible.builtin.apt:
        name: "*"
        state: latest
      check_mode: true
      register: packages
      tags:
        - skip_ansible_lint

    - name: Ensure no packages need update
      ansible.builtin.assert:
        that: "'0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.' in packages.stdout_lines"
        msg: "{{ packages.stdout_lines }}"

    ##
    # Configuration
    ##
    - name: Get the localtime information
      ansible.builtin.stat:
        path: /etc/localtime
      register: _timezone

    - name: Ensure the timezone is set properly
      ansible.builtin.assert:
        that: _timezone.stat.lnk_target == '/usr/share/zoneinfo/' + (timezone | default('Etc/UTC'))
        msg: Expected {{ _timezone.stat.lnk_target }} to point to /usr/share/zoneinfo/{{ timezone | default('Etc/UTC') }}
