---
- name: Setup apt
  import_tasks: tasks/_setup_apt.yml

- name: Ensure all packages are up to date
  apt:
    upgrade: safe
    force_apt_get: true
    autoclean: true
    autoremove: true
    update_cache: true

- name: Install required packages
  apt:
    name:
      - debootstrap
      - dosfstools
      - gdisk
      - linux-headers-{{ ansible_facts.kernel }}
      - mokutil
      - parted
      - python3-pexpect

- name: Install zfs packages
  apt:
    name: zfs-dkms
    default_release: "{{ enable_backports | ternary(ansible_distribution_release + '-backports', omit) }}"

- name: Ensure zfs modules are loaded
  community.general.modprobe:
    name: zfs
    state: present

# This needs to be done after loading the zfs module
# otherwise multiple services will fail
- name: Install zfs utils
  apt:
    name: zfsutils-linux
    default_release: "{{ enable_backports | ternary(ansible_distribution_release + '-backports', omit) }}"

- name: Configure sshd to allow connecting directly inside the chroot
  notify: Restart sshd
  ansible.builtin.blockinfile:
    block: |
      Port 8922
      Match LocalPort 8922
        ChrootDirectory /mnt
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -T -C lport=8922 -f %s

- name: Force handlers to run
  meta: flush_handlers
