---
- name: Setup apt proxy
  template:
    src: apt-proxy.j2
    dest: /etc/apt/apt.conf.d/80-use-proxy
    owner: root
    group: root
    mode: "0o644"
  when: apt_proxy_url is defined

- name: Remove default apt lists
  file:
    name: /etc/apt/sources.list
    state: absent

- name: Enable contrib repositories
  apt_repository:
    repo: deb http://deb.debian.org/debian {{ ansible_distribution_release }} main contrib
    filename: debian
    state: present

- name: Ensure all packages are up to date
  apt:
    upgrade: safe
    force_apt_get: true
    autoclean: true
    autoremove: true
    update_cache: true

- name: Install required packages
  apt:
    name:
      - debootstrap
      - dosfstools
      - gdisk
      - mokutil
      - parted
      - python3-pexpect
      - zfs-dkms

- name: Ensure zfs modules are loaded
  community.general.modprobe:
    name: zfs
    state: present

# This needs to be done after loading the zfs module
# otherwise multiple services will fail
- name: Install zfs utils
  apt:
    name: zfsutils-linux

- name: Configure sshd to allow connecting directly inside the chroot
  notify: Restart sshd
  ansible.builtin.blockinfile:
    block: |
      Port 8922
      Match LocalPort 8922
        ChrootDirectory /mnt
    path: /etc/ssh/sshd_config
    validate: /usr/sbin/sshd -T -C lport=8922 -f %s

- name: Force handlers to run
  meta: flush_handlers
