---
external:
  hosts:
    debian-zfs-root.test:
      admin_username: testuser
      admin_password: "{{ admin_password_clear | ansible.builtin.password_hash }}"
      admin_public_key: "{{ lookup('ansible.builtin.file', molecule_ephemeral_directory + '/keys/id_rsa.pub') }}"
      dropbear_port: 4748
      enable_backports: true
      fqdn: debian-zfs-root.test
      mokutil_password: "{{ admin_password }}"
      network_interface: enp1s0
      root_disks:
        - vda
      ssh_port: 22
      zfs_pool_password: password

      # Testing options
      admin_password_clear: testuser
      debian_mirror: "{{ lookup('ansible.builtin.env', 'DEBIAN_MIRROR') }}"
